apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    ver: v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
      ver: v1
  template:
    metadata:
      labels:
        app: hello-world
        ver: v1
    spec:
      containers:
      - name: hello-world
        image: kubejack/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
